### ISSUE TITLE
Accept files as arguments for git add command

### ISSUE THREAD

**Issue by AbirHamzi** [hatembentayeb/git_helper#1]
**Wished Behavior**
Call the script as following to add specific files:
```
$ script.sh -a "commit_msg" file1 file2
```
Call the script as following to add all changed files:
```
$ script.sh -A "commit_msg" 
```

**Comment by hatembentayeb** [comment]
I think that we are recreating git add -A feature 
what about combing git add and git commit together
`script -a f1,f2,f3 -c "commit"`

**Comment by AbirHamzi** [comment]
Yes it's okay with that solution too , according to your solution git add all how is going to be ?

**Comment by hatembentayeb** [comment]
we will make `-all` so the script will be 
`script -all -c "commit"`
